**/.git
**/.idea
**/.DS_Store
**/node_modules
.env
.env.*
**/*.env

frontend
ai-service
docs
docker-compose.yml
Makefile
data/expected_results*

backend/tmp
backend/bin
backend/.air.toml
backend/**/*_test.go
backend/Dockerfile
backend/Dockerfile.dockerignore
backend/railway.json
