*

!backend
!data
data/*
!data/readings.csv
!data/events.csv

backend/.idea
backend/tmp
backend/bin
backend/.air.toml
backend/**/*_test.go
backend/Dockerfile
backend/Dockerfile.dockerignore
backend/.dockerignore
