from enum import StrEnum


class EventType(StrEnum):
    OPERATIONAL_CHANGE = "OPERATIONAL_CHANGE"
    SCHEDULED_OUTAGE = "SCHEDULED_OUTAGE"
    DATA_QUALITY = "DATA_QUALITY"
    MAINTENANCE = "MAINTENANCE"
    UNKNOWN = "UNKNOWN"


class AnomalyType(StrEnum):
    REAL_ANOMALY = "REAL_ANOMALY"
    EXPLAINABLE_ANOMALY = "EXPLAINABLE_ANOMALY"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    DATA_QUALITY = "DATA_QUALITY"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class SignalKind(StrEnum):
    CONSUMPTION_SURGE = "CONSUMPTION_SURGE"
    CONSUMPTION_DROP = "CONSUMPTION_DROP"
    VOLTAGE_OUT_OF_RANGE = "VOLTAGE_OUT_OF_RANGE"
    VOLTAGE_INSTABILITY = "VOLTAGE_INSTABILITY"
    LOW_POWER_FACTOR = "LOW_POWER_FACTOR"
    OVERCURRENT = "OVERCURRENT"
