// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const advanceAnalysis = `-- name: AdvanceAnalysis :exec
UPDATE analysis
SET str_status_analysis     = 'RUNNING',
    str_current_step_analysis = $1::text,
    num_progress_analysis   = $2,
    dtm_started_at_analysis = COALESCE(dtm_started_at_analysis, now())
WHERE uid_analysis = $3
`

type AdvanceAnalysisParams struct {
	Step     string
	Progress int16
	ID       uuid.UUID
}

// Marca el paso actual del worker (lo que muestra el stepper del frontend).
// COALESCE conserva la hora de inicio del primer paso.
func (q *Queries) AdvanceAnalysis(ctx context.Context, arg AdvanceAnalysisParams) error {
	_, err := q.db.Exec(ctx, advanceAnalysis, arg.Step, arg.Progress, arg.ID)
	return err
}

const completeAnalysis = `-- name: CompleteAnalysis :exec
UPDATE analysis
SET str_status_analysis        = 'COMPLETED',
    str_current_step_analysis  = 'completed',
    num_progress_analysis      = 100,
    str_provider_analysis      = $1,
    num_meters_analyzed        = $2,
    num_anomalies_analysis     = $3,
    num_high_priority_analysis = $4,
    dtm_finished_at_analysis   = now()
WHERE uid_analysis = $5
`

type CompleteAnalysisParams struct {
	Provider       *string
	MetersAnalyzed int32
	Anomalies      int32
	HighPriority   int32
	ID             uuid.UUID
}

func (q *Queries) CompleteAnalysis(ctx context.Context, arg CompleteAnalysisParams) error {
	_, err := q.db.Exec(ctx, completeAnalysis,
		arg.Provider,
		arg.MetersAnalyzed,
		arg.Anomalies,
		arg.HighPriority,
		arg.ID,
	)
	return err
}

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO analysis (uid_user)
VALUES ($1)
RETURNING uid_analysis, num_id_analysis, str_status_analysis, str_current_step_analysis, num_progress_analysis, str_provider_analysis, num_meters_analyzed, num_anomalies_analysis, num_high_priority_analysis, str_error_analysis, uid_user, dtm_started_at_analysis, dtm_finished_at_analysis, dtm_created_at, dtm_updated_at
`

func (q *Queries) CreateAnalysis(ctx context.Context, userID *uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, createAnalysis, userID)
	var i Analysis
	err := row.Scan(
		&i.UidAnalysis,
		&i.NumIDAnalysis,
		&i.StrStatusAnalysis,
		&i.StrCurrentStepAnalysis,
		&i.NumProgressAnalysis,
		&i.StrProviderAnalysis,
		&i.NumMetersAnalyzed,
		&i.NumAnomaliesAnalysis,
		&i.NumHighPriorityAnalysis,
		&i.StrErrorAnalysis,
		&i.UidUser,
		&i.DtmStartedAtAnalysis,
		&i.DtmFinishedAtAnalysis,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const failAnalysis = `-- name: FailAnalysis :exec
UPDATE analysis
SET str_status_analysis      = 'FAILED',
    str_error_analysis       = $1,
    dtm_finished_at_analysis = now()
WHERE uid_analysis = $2
`

type FailAnalysisParams struct {
	ErrorMessage *string
	ID           uuid.UUID
}

func (q *Queries) FailAnalysis(ctx context.Context, arg FailAnalysisParams) error {
	_, err := q.db.Exec(ctx, failAnalysis, arg.ErrorMessage, arg.ID)
	return err
}

const failInterruptedAnalyses = `-- name: FailInterruptedAnalyses :execrows
UPDATE analysis
SET str_status_analysis      = 'FAILED',
    str_error_analysis       = 'interrupted by a service restart',
    dtm_finished_at_analysis = now()
WHERE str_status_analysis IN ('PENDING', 'RUNNING')
`

// Al arrancar el backend: un análisis que quedó PENDING o RUNNING fue interrumpido por un reinicio.
func (q *Queries) FailInterruptedAnalyses(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failInterruptedAnalyses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAnalysis = `-- name: GetActiveAnalysis :one
SELECT uid_analysis, num_id_analysis, str_status_analysis, str_current_step_analysis, num_progress_analysis, str_provider_analysis, num_meters_analyzed, num_anomalies_analysis, num_high_priority_analysis, str_error_analysis, uid_user, dtm_started_at_analysis, dtm_finished_at_analysis, dtm_created_at, dtm_updated_at
FROM analysis
WHERE str_status_analysis IN ('PENDING', 'RUNNING')
ORDER BY dtm_created_at DESC
LIMIT 1
`

// Un análisis en curso (PENDING o RUNNING): evita lanzar dos a la vez.
func (q *Queries) GetActiveAnalysis(ctx context.Context) (Analysis, error) {
	row := q.db.QueryRow(ctx, getActiveAnalysis)
	var i Analysis
	err := row.Scan(
		&i.UidAnalysis,
		&i.NumIDAnalysis,
		&i.StrStatusAnalysis,
		&i.StrCurrentStepAnalysis,
		&i.NumProgressAnalysis,
		&i.StrProviderAnalysis,
		&i.NumMetersAnalyzed,
		&i.NumAnomaliesAnalysis,
		&i.NumHighPriorityAnalysis,
		&i.StrErrorAnalysis,
		&i.UidUser,
		&i.DtmStartedAtAnalysis,
		&i.DtmFinishedAtAnalysis,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT uid_analysis, num_id_analysis, str_status_analysis, str_current_step_analysis, num_progress_analysis, str_provider_analysis, num_meters_analyzed, num_anomalies_analysis, num_high_priority_analysis, str_error_analysis, uid_user, dtm_started_at_analysis, dtm_finished_at_analysis, dtm_created_at, dtm_updated_at
FROM analysis
WHERE uid_analysis = $1
`

func (q *Queries) GetAnalysis(ctx context.Context, uidAnalysis uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, uidAnalysis)
	var i Analysis
	err := row.Scan(
		&i.UidAnalysis,
		&i.NumIDAnalysis,
		&i.StrStatusAnalysis,
		&i.StrCurrentStepAnalysis,
		&i.NumProgressAnalysis,
		&i.StrProviderAnalysis,
		&i.NumMetersAnalyzed,
		&i.NumAnomaliesAnalysis,
		&i.NumHighPriorityAnalysis,
		&i.StrErrorAnalysis,
		&i.UidUser,
		&i.DtmStartedAtAnalysis,
		&i.DtmFinishedAtAnalysis,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const getLatestAnalysis = `-- name: GetLatestAnalysis :one
SELECT uid_analysis, num_id_analysis, str_status_analysis, str_current_step_analysis, num_progress_analysis, str_provider_analysis, num_meters_analyzed, num_anomalies_analysis, num_high_priority_analysis, str_error_analysis, uid_user, dtm_started_at_analysis, dtm_finished_at_analysis, dtm_created_at, dtm_updated_at
FROM analysis
ORDER BY dtm_created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAnalysis(ctx context.Context) (Analysis, error) {
	row := q.db.QueryRow(ctx, getLatestAnalysis)
	var i Analysis
	err := row.Scan(
		&i.UidAnalysis,
		&i.NumIDAnalysis,
		&i.StrStatusAnalysis,
		&i.StrCurrentStepAnalysis,
		&i.NumProgressAnalysis,
		&i.StrProviderAnalysis,
		&i.NumMetersAnalyzed,
		&i.NumAnomaliesAnalysis,
		&i.NumHighPriorityAnalysis,
		&i.StrErrorAnalysis,
		&i.UidUser,
		&i.DtmStartedAtAnalysis,
		&i.DtmFinishedAtAnalysis,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const getLatestCompletedAnalysisID = `-- name: GetLatestCompletedAnalysisID :one
SELECT uid_analysis
FROM analysis
WHERE str_status_analysis = 'COMPLETED'
ORDER BY dtm_finished_at_analysis DESC
LIMIT 1
`

// Análisis cuyas anomalías se muestran por defecto: el último que terminó bien (uno en curso aún no tiene resultados).
func (q *Queries) GetLatestCompletedAnalysisID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedAnalysisID)
	var uid_analysis uuid.UUID
	err := row.Scan(&uid_analysis)
	return uid_analysis, err
}

const refreshMeterStatuses = `-- name: RefreshMeterStatuses :exec
UPDATE meter m
SET str_status_meter = CASE
                           WHEN EXISTS (SELECT 1
                                        FROM anomaly a
                                        WHERE a.uid_analysis = $1
                                          AND a.uid_meter = m.uid_meter
                                          AND a.str_type_anomaly = 'REAL_ANOMALY'
                                          AND a.str_severity_anomaly = 'HIGH') THEN 'CRITICAL'
                           WHEN EXISTS (SELECT 1
                                        FROM anomaly a
                                        WHERE a.uid_analysis = $1
                                          AND a.uid_meter = m.uid_meter
                                          AND a.str_type_anomaly IN ('REAL_ANOMALY', 'DATA_QUALITY')) THEN 'ALERT'
                           ELSE 'OK'
    END::meter_status
WHERE m.dtm_deleted_at_meter IS NULL
  AND ($2::uuid[] IS NULL OR m.uid_meter = ANY ($2::uuid[]))
`

type RefreshMeterStatusesParams struct {
	AnalysisID uuid.UUID
	MeterIds   []uuid.UUID
}

// Estado de cada medidor analizado según sus anomalías en este análisis. meter_ids NULL = toda la flota activa.
func (q *Queries) RefreshMeterStatuses(ctx context.Context, arg RefreshMeterStatusesParams) error {
	_, err := q.db.Exec(ctx, refreshMeterStatuses, arg.AnalysisID, arg.MeterIds)
	return err
}
