// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anomaly.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getAnomaly = `-- name: GetAnomaly :one
SELECT a.uid_anomaly, a.num_id_anomaly, a.uid_analysis, a.uid_meter, a.uid_event, a.str_type_anomaly, a.str_severity_anomaly, a.str_status_anomaly, a.dec_confidence_anomaly, a.dec_priority_score_anomaly, a.dec_baseline_kwh_anomaly, a.dec_current_kwh_anomaly, a.dec_variation_pct_anomaly, a.dtm_window_start_anomaly, a.dtm_window_end_anomaly, a.str_reason_anomaly, a.str_recommended_action_anomaly, a.arr_changed_variables_anomaly, a.json_evidence_anomaly, a.str_resolution_note_anomaly, a.dtm_detected_at_anomaly, a.dtm_created_at, a.dtm_updated_at, a.str_rule_id_anomaly,
       m.str_code_meter,
       m.str_name_meter,
       m.str_location_meter,
       e.str_type_event,
       e.dtm_timestamp_event,
       e.str_description_event
FROM anomaly a
         JOIN meter m ON m.uid_meter = a.uid_meter
         LEFT JOIN event e ON e.uid_event = a.uid_event
WHERE a.uid_anomaly = $1
`

type GetAnomalyRow struct {
	UidAnomaly                  uuid.UUID
	NumIDAnomaly                int32
	UidAnalysis                 uuid.UUID
	UidMeter                    uuid.UUID
	UidEvent                    *uuid.UUID
	StrTypeAnomaly              AnomalyType
	StrSeverityAnomaly          AnomalySeverity
	StrStatusAnomaly            AnomalyStatus
	DecConfidenceAnomaly        float64
	DecPriorityScoreAnomaly     float64
	DecBaselineKwhAnomaly       *float64
	DecCurrentKwhAnomaly        *float64
	DecVariationPctAnomaly      *float64
	DtmWindowStartAnomaly       *time.Time
	DtmWindowEndAnomaly         *time.Time
	StrReasonAnomaly            string
	StrRecommendedActionAnomaly string
	ArrChangedVariablesAnomaly  []string
	JsonEvidenceAnomaly         json.RawMessage
	StrResolutionNoteAnomaly    *string
	DtmDetectedAtAnomaly        time.Time
	DtmCreatedAt                time.Time
	DtmUpdatedAt                time.Time
	StrRuleIDAnomaly            string
	StrCodeMeter                string
	StrNameMeter                string
	StrLocationMeter            string
	StrTypeEvent                *EventType
	DtmTimestampEvent           *time.Time
	StrDescriptionEvent         *string
}

// Detalle completo para la pantalla de investigación, con el medidor y el evento relacionado.
func (q *Queries) GetAnomaly(ctx context.Context, uidAnomaly uuid.UUID) (GetAnomalyRow, error) {
	row := q.db.QueryRow(ctx, getAnomaly, uidAnomaly)
	var i GetAnomalyRow
	err := row.Scan(
		&i.UidAnomaly,
		&i.NumIDAnomaly,
		&i.UidAnalysis,
		&i.UidMeter,
		&i.UidEvent,
		&i.StrTypeAnomaly,
		&i.StrSeverityAnomaly,
		&i.StrStatusAnomaly,
		&i.DecConfidenceAnomaly,
		&i.DecPriorityScoreAnomaly,
		&i.DecBaselineKwhAnomaly,
		&i.DecCurrentKwhAnomaly,
		&i.DecVariationPctAnomaly,
		&i.DtmWindowStartAnomaly,
		&i.DtmWindowEndAnomaly,
		&i.StrReasonAnomaly,
		&i.StrRecommendedActionAnomaly,
		&i.ArrChangedVariablesAnomaly,
		&i.JsonEvidenceAnomaly,
		&i.StrResolutionNoteAnomaly,
		&i.DtmDetectedAtAnomaly,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
		&i.StrRuleIDAnomaly,
		&i.StrCodeMeter,
		&i.StrNameMeter,
		&i.StrLocationMeter,
		&i.StrTypeEvent,
		&i.DtmTimestampEvent,
		&i.StrDescriptionEvent,
	)
	return i, err
}

const insertAnomaly = `-- name: InsertAnomaly :exec
INSERT INTO anomaly (uid_analysis, uid_meter, uid_event, str_type_anomaly, str_severity_anomaly, str_rule_id_anomaly,
                     dec_confidence_anomaly, dec_priority_score_anomaly, dec_baseline_kwh_anomaly,
                     dec_current_kwh_anomaly, dec_variation_pct_anomaly, dtm_window_start_anomaly,
                     dtm_window_end_anomaly, str_reason_anomaly, str_recommended_action_anomaly,
                     arr_changed_variables_anomaly, json_evidence_anomaly, dtm_detected_at_anomaly)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12, $13,
        $14, $15, $16, $17,
        $18)
`

type InsertAnomalyParams struct {
	AnalysisID        uuid.UUID
	MeterID           uuid.UUID
	EventID           *uuid.UUID
	Type              AnomalyType
	Severity          AnomalySeverity
	RuleID            string
	Confidence        float64
	PriorityScore     float64
	BaselineKwh       *float64
	CurrentKwh        *float64
	VariationPct      *float64
	WindowStart       *time.Time
	WindowEnd         *time.Time
	Reason            string
	RecommendedAction string
	ChangedVariables  []string
	Evidence          json.RawMessage
	DetectedAt        time.Time
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) error {
	_, err := q.db.Exec(ctx, insertAnomaly,
		arg.AnalysisID,
		arg.MeterID,
		arg.EventID,
		arg.Type,
		arg.Severity,
		arg.RuleID,
		arg.Confidence,
		arg.PriorityScore,
		arg.BaselineKwh,
		arg.CurrentKwh,
		arg.VariationPct,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Reason,
		arg.RecommendedAction,
		arg.ChangedVariables,
		arg.Evidence,
		arg.DetectedAt,
	)
	return err
}

const listAnomalies = `-- name: ListAnomalies :many
SELECT a.uid_anomaly,
       a.num_id_anomaly,
       a.uid_meter,
       m.str_code_meter,
       m.str_name_meter,
       a.str_type_anomaly,
       a.str_severity_anomaly,
       a.str_status_anomaly,
       a.str_rule_id_anomaly,
       a.dec_confidence_anomaly,
       a.dec_priority_score_anomaly,
       a.dec_variation_pct_anomaly,
       a.dtm_detected_at_anomaly,
       a.str_reason_anomaly
FROM anomaly a
         JOIN meter m ON m.uid_meter = a.uid_meter
WHERE a.uid_analysis = $1
  AND ($2::anomaly_type IS NULL OR a.str_type_anomaly = $2)
  AND ($3::anomaly_severity IS NULL OR a.str_severity_anomaly = $3)
  AND ($4::anomaly_status IS NULL OR a.str_status_anomaly = $4)
ORDER BY a.dec_priority_score_anomaly DESC, a.num_id_anomaly
`

type ListAnomaliesParams struct {
	AnalysisID uuid.UUID
	Type       *AnomalyType
	Severity   *AnomalySeverity
	Status     *AnomalyStatus
}

type ListAnomaliesRow struct {
	UidAnomaly              uuid.UUID
	NumIDAnomaly            int32
	UidMeter                uuid.UUID
	StrCodeMeter            string
	StrNameMeter            string
	StrTypeAnomaly          AnomalyType
	StrSeverityAnomaly      AnomalySeverity
	StrStatusAnomaly        AnomalyStatus
	StrRuleIDAnomaly        string
	DecConfidenceAnomaly    float64
	DecPriorityScoreAnomaly float64
	DecVariationPctAnomaly  *float64
	DtmDetectedAtAnomaly    time.Time
	StrReasonAnomaly        string
}

// Anomalías de un análisis, de la más a la menos prioritaria, con el código y nombre del medidor para la tabla.
func (q *Queries) ListAnomalies(ctx context.Context, arg ListAnomaliesParams) ([]ListAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, listAnomalies,
		arg.AnalysisID,
		arg.Type,
		arg.Severity,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnomaliesRow
	for rows.Next() {
		var i ListAnomaliesRow
		if err := rows.Scan(
			&i.UidAnomaly,
			&i.NumIDAnomaly,
			&i.UidMeter,
			&i.StrCodeMeter,
			&i.StrNameMeter,
			&i.StrTypeAnomaly,
			&i.StrSeverityAnomaly,
			&i.StrStatusAnomaly,
			&i.StrRuleIDAnomaly,
			&i.DecConfidenceAnomaly,
			&i.DecPriorityScoreAnomaly,
			&i.DecVariationPctAnomaly,
			&i.DtmDetectedAtAnomaly,
			&i.StrReasonAnomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnomalyStatus = `-- name: UpdateAnomalyStatus :one
UPDATE anomaly
SET str_status_anomaly          = $1,
    str_resolution_note_anomaly = COALESCE($2, str_resolution_note_anomaly)
WHERE uid_anomaly = $3
RETURNING uid_anomaly, num_id_anomaly, uid_analysis, uid_meter, uid_event, str_type_anomaly, str_severity_anomaly, str_status_anomaly, dec_confidence_anomaly, dec_priority_score_anomaly, dec_baseline_kwh_anomaly, dec_current_kwh_anomaly, dec_variation_pct_anomaly, dtm_window_start_anomaly, dtm_window_end_anomaly, str_reason_anomaly, str_recommended_action_anomaly, arr_changed_variables_anomaly, json_evidence_anomaly, str_resolution_note_anomaly, dtm_detected_at_anomaly, dtm_created_at, dtm_updated_at, str_rule_id_anomaly
`

type UpdateAnomalyStatusParams struct {
	Status         AnomalyStatus
	ResolutionNote *string
	ID             uuid.UUID
}

// La acción del operador. La nota de resolución solo se reemplaza si llega una nueva.
func (q *Queries) UpdateAnomalyStatus(ctx context.Context, arg UpdateAnomalyStatusParams) (Anomaly, error) {
	row := q.db.QueryRow(ctx, updateAnomalyStatus, arg.Status, arg.ResolutionNote, arg.ID)
	var i Anomaly
	err := row.Scan(
		&i.UidAnomaly,
		&i.NumIDAnomaly,
		&i.UidAnalysis,
		&i.UidMeter,
		&i.UidEvent,
		&i.StrTypeAnomaly,
		&i.StrSeverityAnomaly,
		&i.StrStatusAnomaly,
		&i.DecConfidenceAnomaly,
		&i.DecPriorityScoreAnomaly,
		&i.DecBaselineKwhAnomaly,
		&i.DecCurrentKwhAnomaly,
		&i.DecVariationPctAnomaly,
		&i.DtmWindowStartAnomaly,
		&i.DtmWindowEndAnomaly,
		&i.StrReasonAnomaly,
		&i.StrRecommendedActionAnomaly,
		&i.ArrChangedVariablesAnomaly,
		&i.JsonEvidenceAnomaly,
		&i.StrResolutionNoteAnomaly,
		&i.DtmDetectedAtAnomaly,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
		&i.StrRuleIDAnomaly,
	)
	return i, err
}
