// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertEvents = `-- name: InsertEvents :execrows
INSERT INTO event (uid_meter, dtm_timestamp_event, str_type_event, str_description_event)
SELECT unnest($1::uuid[]),
       unnest($2::timestamptz[]),
       unnest($3::text[])::event_type,
       unnest($4::text[])
ON CONFLICT (uid_meter, dtm_timestamp_event, str_type_event) DO NOTHING
`

type InsertEventsParams struct {
	MeterIds     []uuid.UUID
	Timestamps   []time.Time
	Types        []string
	Descriptions []string
}

// Mismo patrón que InsertReadings; el tipo llega como text[] y se convierte al enum en SQL
func (q *Queries) InsertEvents(ctx context.Context, arg InsertEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvents,
		arg.MeterIds,
		arg.Timestamps,
		arg.Types,
		arg.Descriptions,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
