// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeImportBatch = `-- name: CompleteImportBatch :exec
UPDATE import_batch
SET num_inserted_import_batch        = $1,
    num_skipped_import_batch         = $2,
    num_meters_created_import_batch  = $3,
    num_meters_restored_import_batch = $4
WHERE uid_import_batch = $5
`

type CompleteImportBatchParams struct {
	Inserted       int32
	Skipped        int32
	MetersCreated  int32
	MetersRestored int32
	ID             uuid.UUID
}

func (q *Queries) CompleteImportBatch(ctx context.Context, arg CompleteImportBatchParams) error {
	_, err := q.db.Exec(ctx, completeImportBatch,
		arg.Inserted,
		arg.Skipped,
		arg.MetersCreated,
		arg.MetersRestored,
		arg.ID,
	)
	return err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batch (str_kind_import_batch, str_status_import_batch, str_file_name_import_batch,
                          num_file_size_import_batch, str_checksum_import_batch, num_rows_import_batch,
                          str_error_code_import_batch, str_error_import_batch, uid_user)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING uid_import_batch, num_id_import_batch, str_kind_import_batch, str_status_import_batch, str_file_name_import_batch, num_file_size_import_batch, str_checksum_import_batch, num_rows_import_batch, num_inserted_import_batch, num_skipped_import_batch, num_meters_created_import_batch, num_meters_restored_import_batch, str_error_code_import_batch, str_error_import_batch, uid_user, dtm_created_at
`

type CreateImportBatchParams struct {
	Kind      ImportKind
	Status    ImportStatus
	FileName  string
	FileSize  int64
	Checksum  string
	Rows      int32
	ErrorCode *string
	Error     *string
	UserID    *uuid.UUID
}

// Una importación exitosa crea el lote al inicio de su transacción (las filas lo referencian) y un fallo lo crea ya cerrado.
func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.Kind,
		arg.Status,
		arg.FileName,
		arg.FileSize,
		arg.Checksum,
		arg.Rows,
		arg.ErrorCode,
		arg.Error,
		arg.UserID,
	)
	var i ImportBatch
	err := row.Scan(
		&i.UidImportBatch,
		&i.NumIDImportBatch,
		&i.StrKindImportBatch,
		&i.StrStatusImportBatch,
		&i.StrFileNameImportBatch,
		&i.NumFileSizeImportBatch,
		&i.StrChecksumImportBatch,
		&i.NumRowsImportBatch,
		&i.NumInsertedImportBatch,
		&i.NumSkippedImportBatch,
		&i.NumMetersCreatedImportBatch,
		&i.NumMetersRestoredImportBatch,
		&i.StrErrorCodeImportBatch,
		&i.StrErrorImportBatch,
		&i.UidUser,
		&i.DtmCreatedAt,
	)
	return i, err
}

const findCompletedImportByChecksum = `-- name: FindCompletedImportByChecksum :one
SELECT uid_import_batch, dtm_created_at
FROM import_batch
WHERE str_kind_import_batch = $1
  AND str_checksum_import_batch = $2
  AND str_status_import_batch = 'COMPLETED'
ORDER BY dtm_created_at DESC
LIMIT 1
`

type FindCompletedImportByChecksumParams struct {
	Kind     ImportKind
	Checksum string
}

type FindCompletedImportByChecksumRow struct {
	UidImportBatch uuid.UUID
	DtmCreatedAt   time.Time
}

// Detecta que el mismo archivo ya se importó con éxito: se avisa al usuario, pero se permite reimportar (es idempotente).
func (q *Queries) FindCompletedImportByChecksum(ctx context.Context, arg FindCompletedImportByChecksumParams) (FindCompletedImportByChecksumRow, error) {
	row := q.db.QueryRow(ctx, findCompletedImportByChecksum, arg.Kind, arg.Checksum)
	var i FindCompletedImportByChecksumRow
	err := row.Scan(&i.UidImportBatch, &i.DtmCreatedAt)
	return i, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT b.uid_import_batch, b.num_id_import_batch, b.str_kind_import_batch, b.str_status_import_batch, b.str_file_name_import_batch, b.num_file_size_import_batch, b.str_checksum_import_batch, b.num_rows_import_batch, b.num_inserted_import_batch, b.num_skipped_import_batch, b.num_meters_created_import_batch, b.num_meters_restored_import_batch, b.str_error_code_import_batch, b.str_error_import_batch, b.uid_user, b.dtm_created_at, u.str_name_user
FROM import_batch b
         LEFT JOIN app_user u ON u.uid_user = b.uid_user
ORDER BY b.dtm_created_at DESC
LIMIT $1
`

type ListImportBatchesRow struct {
	UidImportBatch               uuid.UUID
	NumIDImportBatch             int32
	StrKindImportBatch           ImportKind
	StrStatusImportBatch         ImportStatus
	StrFileNameImportBatch       string
	NumFileSizeImportBatch       int64
	StrChecksumImportBatch       string
	NumRowsImportBatch           int32
	NumInsertedImportBatch       int32
	NumSkippedImportBatch        int32
	NumMetersCreatedImportBatch  int32
	NumMetersRestoredImportBatch int32
	StrErrorCodeImportBatch      *string
	StrErrorImportBatch          *string
	UidUser                      *uuid.UUID
	DtmCreatedAt                 time.Time
	StrNameUser                  *string
}

func (q *Queries) ListImportBatches(ctx context.Context, pageLimit int32) ([]ListImportBatchesRow, error) {
	rows, err := q.db.Query(ctx, listImportBatches, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportBatchesRow
	for rows.Next() {
		var i ListImportBatchesRow
		if err := rows.Scan(
			&i.UidImportBatch,
			&i.NumIDImportBatch,
			&i.StrKindImportBatch,
			&i.StrStatusImportBatch,
			&i.StrFileNameImportBatch,
			&i.NumFileSizeImportBatch,
			&i.StrChecksumImportBatch,
			&i.NumRowsImportBatch,
			&i.NumInsertedImportBatch,
			&i.NumSkippedImportBatch,
			&i.NumMetersCreatedImportBatch,
			&i.NumMetersRestoredImportBatch,
			&i.StrErrorCodeImportBatch,
			&i.StrErrorImportBatch,
			&i.UidUser,
			&i.DtmCreatedAt,
			&i.StrNameUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
