// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kpi.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT summary.meters_count::bigint            AS meters_count,
       summary.meters_with_alerts::bigint      AS meters_with_alerts,
       summary.readings_count::bigint          AS readings_count,
       summary.total_kwh::double precision     AS total_kwh,
       summary.open_anomalies::bigint          AS open_anomalies,
       summary.high_priority_anomalies::bigint AS high_priority_anomalies
FROM fn_dashboard_summary() AS summary
`

type GetDashboardSummaryRow struct {
	MetersCount           int64
	MetersWithAlerts      int64
	ReadingsCount         int64
	TotalKwh              float64
	OpenAnomalies         int64
	HighPriorityAnomalies int64
}

func (q *Queries) GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.MetersCount,
		&i.MetersWithAlerts,
		&i.ReadingsCount,
		&i.TotalKwh,
		&i.OpenAnomalies,
		&i.HighPriorityAnomalies,
	)
	return i, err
}

const getMeterConsumptionStats = `-- name: GetMeterConsumptionStats :many
SELECT stats.uid_meter::uuid                    AS uid_meter,
       stats.readings_count::bigint             AS readings_count,
       stats.total_kwh::double precision        AS total_kwh,
       stats.baseline_avg_kwh::double precision AS baseline_avg_kwh,
       stats.recent_avg_kwh::double precision   AS recent_avg_kwh,
       stats.variation_pct::double precision    AS variation_pct,
       stats.avg_voltage::double precision      AS avg_voltage,
       stats.min_power_factor::double precision AS min_power_factor,
       stats.first_reading_at::timestamptz      AS first_reading_at,
       stats.last_reading_at::timestamptz       AS last_reading_at
FROM fn_meter_consumption_stats($1, $2,
                                $3, $4) AS stats
`

type GetMeterConsumptionStatsParams struct {
	FromTime     time.Time
	ToTime       time.Time
	BaselineDays int32
	RecentHours  int32
}

type GetMeterConsumptionStatsRow struct {
	UidMeter       uuid.UUID
	ReadingsCount  int64
	TotalKwh       float64
	BaselineAvgKwh float64
	RecentAvgKwh   float64
	VariationPct   float64
	AvgVoltage     float64
	MinPowerFactor float64
	FirstReadingAt time.Time
	LastReadingAt  time.Time
}

// sqlc no deduce las columnas de una función RETURNS TABLE: cada columna se nombra y se castea explícitamente.
func (q *Queries) GetMeterConsumptionStats(ctx context.Context, arg GetMeterConsumptionStatsParams) ([]GetMeterConsumptionStatsRow, error) {
	rows, err := q.db.Query(ctx, getMeterConsumptionStats,
		arg.FromTime,
		arg.ToTime,
		arg.BaselineDays,
		arg.RecentHours,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeterConsumptionStatsRow
	for rows.Next() {
		var i GetMeterConsumptionStatsRow
		if err := rows.Scan(
			&i.UidMeter,
			&i.ReadingsCount,
			&i.TotalKwh,
			&i.BaselineAvgKwh,
			&i.RecentAvgKwh,
			&i.VariationPct,
			&i.AvgVoltage,
			&i.MinPowerFactor,
			&i.FirstReadingAt,
			&i.LastReadingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeterHourlyProfile = `-- name: GetMeterHourlyProfile :many
SELECT profile.hour_of_day::integer          AS hour_of_day,
       profile.avg_kwh::double precision     AS avg_kwh,
       profile.readings_count::bigint        AS readings_count
FROM fn_meter_hourly_profile($1, $2, $3,
                             $4) AS profile
`

type GetMeterHourlyProfileParams struct {
	MeterID  uuid.UUID
	FromTime time.Time
	ToTime   time.Time
	Timezone string
}

type GetMeterHourlyProfileRow struct {
	HourOfDay     int32
	AvgKwh        float64
	ReadingsCount int64
}

func (q *Queries) GetMeterHourlyProfile(ctx context.Context, arg GetMeterHourlyProfileParams) ([]GetMeterHourlyProfileRow, error) {
	rows, err := q.db.Query(ctx, getMeterHourlyProfile,
		arg.MeterID,
		arg.FromTime,
		arg.ToTime,
		arg.Timezone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeterHourlyProfileRow
	for rows.Next() {
		var i GetMeterHourlyProfileRow
		if err := rows.Scan(&i.HourOfDay, &i.AvgKwh, &i.ReadingsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
