// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meter.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countMeters = `-- name: CountMeters :one
SELECT count(*)
FROM meter
WHERE dtm_deleted_at_meter IS NULL
  AND ($1::meter_status IS NULL OR str_status_meter = $1)
  AND ($2::text IS NULL
    OR str_code_meter ILIKE '%' || $2 || '%'
    OR str_name_meter ILIKE '%' || $2 || '%'
    OR str_location_meter ILIKE '%' || $2 || '%')
`

type CountMetersParams struct {
	Status *MeterStatus
	Search *string
}

func (q *Queries) CountMeters(ctx context.Context, arg CountMetersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMeters, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeter = `-- name: CreateMeter :one
INSERT INTO meter (str_code_meter, str_name_meter, str_location_meter, str_sector_meter,
                   dec_nominal_voltage_meter, dec_max_current_meter, dec_contracted_power_kw_meter)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING uid_meter, num_id_meter, str_code_meter, str_name_meter, str_location_meter, str_sector_meter, dec_nominal_voltage_meter, dec_max_current_meter, dec_contracted_power_kw_meter, str_status_meter, dtm_deleted_at_meter, dtm_created_at, dtm_updated_at
`

type CreateMeterParams struct {
	Code              string
	Name              string
	Location          string
	Sector            string
	NominalVoltage    float64
	MaxCurrent        *float64
	ContractedPowerKw *float64
}

func (q *Queries) CreateMeter(ctx context.Context, arg CreateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, createMeter,
		arg.Code,
		arg.Name,
		arg.Location,
		arg.Sector,
		arg.NominalVoltage,
		arg.MaxCurrent,
		arg.ContractedPowerKw,
	)
	var i Meter
	err := row.Scan(
		&i.UidMeter,
		&i.NumIDMeter,
		&i.StrCodeMeter,
		&i.StrNameMeter,
		&i.StrLocationMeter,
		&i.StrSectorMeter,
		&i.DecNominalVoltageMeter,
		&i.DecMaxCurrentMeter,
		&i.DecContractedPowerKwMeter,
		&i.StrStatusMeter,
		&i.DtmDeletedAtMeter,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const getMeterByID = `-- name: GetMeterByID :one
SELECT uid_meter, num_id_meter, str_code_meter, str_name_meter, str_location_meter, str_sector_meter, dec_nominal_voltage_meter, dec_max_current_meter, dec_contracted_power_kw_meter, str_status_meter, dtm_deleted_at_meter, dtm_created_at, dtm_updated_at
FROM meter
WHERE uid_meter = $1
  AND dtm_deleted_at_meter IS NULL
`

func (q *Queries) GetMeterByID(ctx context.Context, uidMeter uuid.UUID) (Meter, error) {
	row := q.db.QueryRow(ctx, getMeterByID, uidMeter)
	var i Meter
	err := row.Scan(
		&i.UidMeter,
		&i.NumIDMeter,
		&i.StrCodeMeter,
		&i.StrNameMeter,
		&i.StrLocationMeter,
		&i.StrSectorMeter,
		&i.DecNominalVoltageMeter,
		&i.DecMaxCurrentMeter,
		&i.DecContractedPowerKwMeter,
		&i.StrStatusMeter,
		&i.DtmDeletedAtMeter,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const listMeters = `-- name: ListMeters :many
SELECT uid_meter, num_id_meter, str_code_meter, str_name_meter, str_location_meter, str_sector_meter, dec_nominal_voltage_meter, dec_max_current_meter, dec_contracted_power_kw_meter, str_status_meter, dtm_deleted_at_meter, dtm_created_at, dtm_updated_at
FROM meter
WHERE dtm_deleted_at_meter IS NULL
  AND ($1::meter_status IS NULL OR str_status_meter = $1)
  AND ($2::text IS NULL
    OR str_code_meter ILIKE '%' || $2 || '%'
    OR str_name_meter ILIKE '%' || $2 || '%'
    OR str_location_meter ILIKE '%' || $2 || '%')
ORDER BY CASE
             WHEN $3::text = 'code' AND $4::boolean = false THEN
                 str_code_meter END,
         CASE
             WHEN $3::text = 'code' AND $4::boolean = true THEN
                 str_code_meter END DESC,
         CASE
             WHEN $3::text = 'name' AND $4::boolean = false THEN
                 str_name_meter END,
         CASE
             WHEN $3::text = 'name' AND $4::boolean = true THEN
                 str_name_meter END DESC,
         CASE
             WHEN $3::text = 'status' AND $4::boolean = false THEN
                 str_status_meter END,
         CASE
             WHEN $3::text = 'status' AND $4::boolean = true THEN
                 str_status_meter END DESC,
         str_code_meter
LIMIT $6 OFFSET $5
`

type ListMetersParams struct {
	Status     *MeterStatus
	Search     *string
	SortBy     string
	SortDesc   bool
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListMeters(ctx context.Context, arg ListMetersParams) ([]Meter, error) {
	rows, err := q.db.Query(ctx, listMeters,
		arg.Status,
		arg.Search,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meter
	for rows.Next() {
		var i Meter
		if err := rows.Scan(
			&i.UidMeter,
			&i.NumIDMeter,
			&i.StrCodeMeter,
			&i.StrNameMeter,
			&i.StrLocationMeter,
			&i.StrSectorMeter,
			&i.DecNominalVoltageMeter,
			&i.DecMaxCurrentMeter,
			&i.DecContractedPowerKwMeter,
			&i.StrStatusMeter,
			&i.DtmDeletedAtMeter,
			&i.DtmCreatedAt,
			&i.DtmUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMeter = `-- name: SoftDeleteMeter :execrows
UPDATE meter
SET dtm_deleted_at_meter = now()
WHERE uid_meter = $1
  AND dtm_deleted_at_meter IS NULL
`

func (q *Queries) SoftDeleteMeter(ctx context.Context, uidMeter uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMeter, uidMeter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMeter = `-- name: UpdateMeter :one
UPDATE meter
SET str_name_meter                = COALESCE($1, str_name_meter),
    str_location_meter            = COALESCE($2, str_location_meter),
    str_sector_meter              = COALESCE($3, str_sector_meter),
    dec_nominal_voltage_meter     = COALESCE($4,
                                             dec_nominal_voltage_meter),
    dec_max_current_meter         = COALESCE($5, dec_max_current_meter),
    dec_contracted_power_kw_meter = COALESCE($6,
                                             dec_contracted_power_kw_meter),
    str_status_meter              = COALESCE($7, str_status_meter)
WHERE uid_meter = $8
  AND dtm_deleted_at_meter IS NULL
RETURNING uid_meter, num_id_meter, str_code_meter, str_name_meter, str_location_meter, str_sector_meter, dec_nominal_voltage_meter, dec_max_current_meter, dec_contracted_power_kw_meter, str_status_meter, dtm_deleted_at_meter, dtm_created_at, dtm_updated_at
`

type UpdateMeterParams struct {
	Name              *string
	Location          *string
	Sector            *string
	NominalVoltage    *float64
	MaxCurrent        *float64
	ContractedPowerKw *float64
	Status            *MeterStatus
	ID                uuid.UUID
}

func (q *Queries) UpdateMeter(ctx context.Context, arg UpdateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, updateMeter,
		arg.Name,
		arg.Location,
		arg.Sector,
		arg.NominalVoltage,
		arg.MaxCurrent,
		arg.ContractedPowerKw,
		arg.Status,
		arg.ID,
	)
	var i Meter
	err := row.Scan(
		&i.UidMeter,
		&i.NumIDMeter,
		&i.StrCodeMeter,
		&i.StrNameMeter,
		&i.StrLocationMeter,
		&i.StrSectorMeter,
		&i.DecNominalVoltageMeter,
		&i.DecMaxCurrentMeter,
		&i.DecContractedPowerKwMeter,
		&i.StrStatusMeter,
		&i.DtmDeletedAtMeter,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}
