// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AnalysisStatus string

const (
	AnalysisStatusPENDING   AnalysisStatus = "PENDING"
	AnalysisStatusRUNNING   AnalysisStatus = "RUNNING"
	AnalysisStatusCOMPLETED AnalysisStatus = "COMPLETED"
	AnalysisStatusFAILED    AnalysisStatus = "FAILED"
)

func (e *AnalysisStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisStatus(s)
	case string:
		*e = AnalysisStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisStatus: %T", src)
	}
	return nil
}

type NullAnalysisStatus struct {
	AnalysisStatus AnalysisStatus
	Valid          bool // Valid is true if AnalysisStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisStatus), nil
}

func (e AnalysisStatus) Valid() bool {
	switch e {
	case AnalysisStatusPENDING,
		AnalysisStatusRUNNING,
		AnalysisStatusCOMPLETED,
		AnalysisStatusFAILED:
		return true
	}
	return false
}

func AllAnalysisStatusValues() []AnalysisStatus {
	return []AnalysisStatus{
		AnalysisStatusPENDING,
		AnalysisStatusRUNNING,
		AnalysisStatusCOMPLETED,
		AnalysisStatusFAILED,
	}
}

type AnomalySeverity string

const (
	AnomalySeverityLOW    AnomalySeverity = "LOW"
	AnomalySeverityMEDIUM AnomalySeverity = "MEDIUM"
	AnomalySeverityHIGH   AnomalySeverity = "HIGH"
)

func (e *AnomalySeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnomalySeverity(s)
	case string:
		*e = AnomalySeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AnomalySeverity: %T", src)
	}
	return nil
}

type NullAnomalySeverity struct {
	AnomalySeverity AnomalySeverity
	Valid           bool // Valid is true if AnomalySeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnomalySeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AnomalySeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnomalySeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnomalySeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnomalySeverity), nil
}

func (e AnomalySeverity) Valid() bool {
	switch e {
	case AnomalySeverityLOW,
		AnomalySeverityMEDIUM,
		AnomalySeverityHIGH:
		return true
	}
	return false
}

func AllAnomalySeverityValues() []AnomalySeverity {
	return []AnomalySeverity{
		AnomalySeverityLOW,
		AnomalySeverityMEDIUM,
		AnomalySeverityHIGH,
	}
}

type AnomalyStatus string

const (
	AnomalyStatusOPEN          AnomalyStatus = "OPEN"
	AnomalyStatusINVESTIGATING AnomalyStatus = "INVESTIGATING"
	AnomalyStatusRESOLVED      AnomalyStatus = "RESOLVED"
	AnomalyStatusDISMISSED     AnomalyStatus = "DISMISSED"
)

func (e *AnomalyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnomalyStatus(s)
	case string:
		*e = AnomalyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnomalyStatus: %T", src)
	}
	return nil
}

type NullAnomalyStatus struct {
	AnomalyStatus AnomalyStatus
	Valid         bool // Valid is true if AnomalyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnomalyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnomalyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnomalyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnomalyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnomalyStatus), nil
}

func (e AnomalyStatus) Valid() bool {
	switch e {
	case AnomalyStatusOPEN,
		AnomalyStatusINVESTIGATING,
		AnomalyStatusRESOLVED,
		AnomalyStatusDISMISSED:
		return true
	}
	return false
}

func AllAnomalyStatusValues() []AnomalyStatus {
	return []AnomalyStatus{
		AnomalyStatusOPEN,
		AnomalyStatusINVESTIGATING,
		AnomalyStatusRESOLVED,
		AnomalyStatusDISMISSED,
	}
}

type AnomalyType string

const (
	AnomalyTypeREALANOMALY        AnomalyType = "REAL_ANOMALY"
	AnomalyTypeEXPLAINABLEANOMALY AnomalyType = "EXPLAINABLE_ANOMALY"
	AnomalyTypeFALSEPOSITIVE      AnomalyType = "FALSE_POSITIVE"
	AnomalyTypeDATAQUALITY        AnomalyType = "DATA_QUALITY"
)

func (e *AnomalyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnomalyType(s)
	case string:
		*e = AnomalyType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnomalyType: %T", src)
	}
	return nil
}

type NullAnomalyType struct {
	AnomalyType AnomalyType
	Valid       bool // Valid is true if AnomalyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnomalyType) Scan(value interface{}) error {
	if value == nil {
		ns.AnomalyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnomalyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnomalyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnomalyType), nil
}

func (e AnomalyType) Valid() bool {
	switch e {
	case AnomalyTypeREALANOMALY,
		AnomalyTypeEXPLAINABLEANOMALY,
		AnomalyTypeFALSEPOSITIVE,
		AnomalyTypeDATAQUALITY:
		return true
	}
	return false
}

func AllAnomalyTypeValues() []AnomalyType {
	return []AnomalyType{
		AnomalyTypeREALANOMALY,
		AnomalyTypeEXPLAINABLEANOMALY,
		AnomalyTypeFALSEPOSITIVE,
		AnomalyTypeDATAQUALITY,
	}
}

type EventType string

const (
	EventTypeOPERATIONALCHANGE EventType = "OPERATIONAL_CHANGE"
	EventTypeSCHEDULEDOUTAGE   EventType = "SCHEDULED_OUTAGE"
	EventTypeDATAQUALITY       EventType = "DATA_QUALITY"
	EventTypeMAINTENANCE       EventType = "MAINTENANCE"
	EventTypeUNKNOWN           EventType = "UNKNOWN"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

func (e EventType) Valid() bool {
	switch e {
	case EventTypeOPERATIONALCHANGE,
		EventTypeSCHEDULEDOUTAGE,
		EventTypeDATAQUALITY,
		EventTypeMAINTENANCE,
		EventTypeUNKNOWN:
		return true
	}
	return false
}

func AllEventTypeValues() []EventType {
	return []EventType{
		EventTypeOPERATIONALCHANGE,
		EventTypeSCHEDULEDOUTAGE,
		EventTypeDATAQUALITY,
		EventTypeMAINTENANCE,
		EventTypeUNKNOWN,
	}
}

type MeterStatus string

const (
	MeterStatusOK       MeterStatus = "OK"
	MeterStatusALERT    MeterStatus = "ALERT"
	MeterStatusCRITICAL MeterStatus = "CRITICAL"
)

func (e *MeterStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeterStatus(s)
	case string:
		*e = MeterStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MeterStatus: %T", src)
	}
	return nil
}

type NullMeterStatus struct {
	MeterStatus MeterStatus
	Valid       bool // Valid is true if MeterStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeterStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MeterStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeterStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeterStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeterStatus), nil
}

func (e MeterStatus) Valid() bool {
	switch e {
	case MeterStatusOK,
		MeterStatusALERT,
		MeterStatusCRITICAL:
		return true
	}
	return false
}

func AllMeterStatusValues() []MeterStatus {
	return []MeterStatus{
		MeterStatusOK,
		MeterStatusALERT,
		MeterStatusCRITICAL,
	}
}

type Analysis struct {
	UidAnalysis             uuid.UUID
	NumIDAnalysis           int32
	StrStatusAnalysis       AnalysisStatus
	StrCurrentStepAnalysis  *string
	NumProgressAnalysis     int16
	StrProviderAnalysis     *string
	NumMetersAnalyzed       int32
	NumAnomaliesAnalysis    int32
	NumHighPriorityAnalysis int32
	StrErrorAnalysis        *string
	UidUser                 *uuid.UUID
	DtmStartedAtAnalysis    *time.Time
	DtmFinishedAtAnalysis   *time.Time
	DtmCreatedAt            time.Time
	DtmUpdatedAt            time.Time
}

type Anomaly struct {
	UidAnomaly                  uuid.UUID
	NumIDAnomaly                int32
	UidAnalysis                 uuid.UUID
	UidMeter                    uuid.UUID
	UidEvent                    *uuid.UUID
	StrTypeAnomaly              AnomalyType
	StrSeverityAnomaly          AnomalySeverity
	StrStatusAnomaly            AnomalyStatus
	DecConfidenceAnomaly        float64
	DecPriorityScoreAnomaly     float64
	DecBaselineKwhAnomaly       *float64
	DecCurrentKwhAnomaly        *float64
	DecVariationPctAnomaly      *float64
	DtmWindowStartAnomaly       *time.Time
	DtmWindowEndAnomaly         *time.Time
	StrReasonAnomaly            string
	StrRecommendedActionAnomaly string
	ArrChangedVariablesAnomaly  []string
	JsonEvidenceAnomaly         json.RawMessage
	StrResolutionNoteAnomaly    *string
	DtmDetectedAtAnomaly        time.Time
	DtmCreatedAt                time.Time
	DtmUpdatedAt                time.Time
	StrRuleIDAnomaly            string
}

type AppUser struct {
	UidUser         uuid.UUID
	NumIDUser       int32
	StrEmailUser    string
	StrPasswordUser string
	StrNameUser     string
	DtmCreatedAt    time.Time
	DtmUpdatedAt    time.Time
}

type Event struct {
	UidEvent            uuid.UUID
	NumIDEvent          int32
	UidMeter            uuid.UUID
	DtmTimestampEvent   time.Time
	StrTypeEvent        EventType
	StrDescriptionEvent string
	DtmCreatedAt        time.Time
	DtmUpdatedAt        time.Time
}

type Meter struct {
	UidMeter                  uuid.UUID
	NumIDMeter                int32
	StrCodeMeter              string
	StrNameMeter              string
	StrLocationMeter          string
	StrSectorMeter            string
	DecNominalVoltageMeter    float64
	DecMaxCurrentMeter        *float64
	DecContractedPowerKwMeter *float64
	StrStatusMeter            MeterStatus
	DtmDeletedAtMeter         *time.Time
	DtmCreatedAt              time.Time
	DtmUpdatedAt              time.Time
}

type Reading struct {
	NumIDReading             int64
	UidMeter                 uuid.UUID
	DtmTimestampReading      time.Time
	DecConsumptionKwhReading float64
	DecVoltageReading        float64
	DecCurrentReading        float64
	DecPowerFactorReading    float64
	StrStatusReading         string
	DtmCreatedAt             time.Time
}
