// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEarliestReadingTime = `-- name: GetEarliestReadingTime :one
SELECT dtm_timestamp_reading
FROM reading
WHERE uid_meter = $1
ORDER BY dtm_timestamp_reading
LIMIT 1
`

// Fecha de la primera lectura del medidor: ancla del período "normal" (baseline) del perfil horario.
// Mismo patrón que GetLatestReadingTime, en orden ascendente: lee UNA fila del índice.
func (q *Queries) GetEarliestReadingTime(ctx context.Context, uidMeter uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getEarliestReadingTime, uidMeter)
	var dtm_timestamp_reading time.Time
	err := row.Scan(&dtm_timestamp_reading)
	return dtm_timestamp_reading, err
}

const getLatestReadingTime = `-- name: GetLatestReadingTime :one
SELECT dtm_timestamp_reading
FROM reading
WHERE uid_meter = $1
ORDER BY dtm_timestamp_reading DESC
LIMIT 1
`

// Fecha de la lectura más reciente de un medidor (para el rango por defecto de la gráfica).
// ORDER BY ... DESC LIMIT 1 recorre el índice (uid_meter, dtm_timestamp_reading) desde el final: lee UNA sola fila.
// Si el medidor no tiene lecturas, :one devuelve pgx.ErrNoRows.
func (q *Queries) GetLatestReadingTime(ctx context.Context, uidMeter uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLatestReadingTime, uidMeter)
	var dtm_timestamp_reading time.Time
	err := row.Scan(&dtm_timestamp_reading)
	return dtm_timestamp_reading, err
}

const insertReadings = `-- name: InsertReadings :execrows
INSERT INTO reading (uid_meter, dtm_timestamp_reading, dec_consumption_kwh_reading, dec_voltage_reading,
                     dec_current_reading, dec_power_factor_reading, str_status_reading)
SELECT unnest($1::uuid[]),
       unnest($2::timestamptz[]),
       unnest($3::double precision[]),
       unnest($4::double precision[]),
       unnest($5::double precision[]),
       unnest($6::double precision[]),
       unnest($7::text[])
ON CONFLICT (uid_meter, dtm_timestamp_reading) DO NOTHING
`

type InsertReadingsParams struct {
	MeterIds     []uuid.UUID
	Timestamps   []time.Time
	Consumptions []float64
	Voltages     []float64
	Currents     []float64
	PowerFactors []float64
	Statuses     []string
}

// Inserción masiva: cada parámetro es un array (una "columna") y unnest los convierte en filas.
// ON CONFLICT hace la importación idempotente: re-importar el mismo archivo no duplica lecturas.
func (q *Queries) InsertReadings(ctx context.Context, arg InsertReadingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReadings,
		arg.MeterIds,
		arg.Timestamps,
		arg.Consumptions,
		arg.Voltages,
		arg.Currents,
		arg.PowerFactors,
		arg.Statuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReadingsByMeter = `-- name: ListReadingsByMeter :many
SELECT dtm_timestamp_reading,
       dec_consumption_kwh_reading,
       dec_voltage_reading,
       dec_current_reading,
       dec_power_factor_reading,
       str_status_reading
FROM reading
WHERE uid_meter = $1
  AND dtm_timestamp_reading >= $2
  AND dtm_timestamp_reading < $3
ORDER BY dtm_timestamp_reading
`

type ListReadingsByMeterParams struct {
	MeterID  uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type ListReadingsByMeterRow struct {
	DtmTimestampReading      time.Time
	DecConsumptionKwhReading float64
	DecVoltageReading        float64
	DecCurrentReading        float64
	DecPowerFactorReading    float64
	StrStatusReading         string
}

// Lecturas de un medidor en el rango [from, to): incluye from, excluye to.
// Usa el índice de uq_reading_meter_timestamp (uid_meter, dtm_timestamp_reading) → no recorre la tabla completa.
func (q *Queries) ListReadingsByMeter(ctx context.Context, arg ListReadingsByMeterParams) ([]ListReadingsByMeterRow, error) {
	rows, err := q.db.Query(ctx, listReadingsByMeter, arg.MeterID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingsByMeterRow
	for rows.Next() {
		var i ListReadingsByMeterRow
		if err := rows.Scan(
			&i.DtmTimestampReading,
			&i.DecConsumptionKwhReading,
			&i.DecVoltageReading,
			&i.DecCurrentReading,
			&i.DecPowerFactorReading,
			&i.StrStatusReading,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
