// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertReadings = `-- name: InsertReadings :execrows
INSERT INTO reading (uid_meter, dtm_timestamp_reading, dec_consumption_kwh_reading, dec_voltage_reading,
                     dec_current_reading, dec_power_factor_reading, str_status_reading)
SELECT unnest($1::uuid[]),
       unnest($2::timestamptz[]),
       unnest($3::double precision[]),
       unnest($4::double precision[]),
       unnest($5::double precision[]),
       unnest($6::double precision[]),
       unnest($7::text[])
ON CONFLICT (uid_meter, dtm_timestamp_reading) DO NOTHING
`

type InsertReadingsParams struct {
	MeterIds     []uuid.UUID
	Timestamps   []time.Time
	Consumptions []float64
	Voltages     []float64
	Currents     []float64
	PowerFactors []float64
	Statuses     []string
}

// Inserción masiva: cada parámetro es un array (una "columna") y unnest los convierte en filas.
// ON CONFLICT hace la importación idempotente: re-importar el mismo archivo no duplica lecturas.
func (q *Queries) InsertReadings(ctx context.Context, arg InsertReadingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReadings,
		arg.MeterIds,
		arg.Timestamps,
		arg.Consumptions,
		arg.Voltages,
		arg.Currents,
		arg.PowerFactors,
		arg.Statuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
