// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT uid_user, num_id_user, str_email_user, str_password_user, str_name_user, dtm_created_at, dtm_updated_at
FROM app_user
WHERE uid_user = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppUser
	err := row.Scan(
		&i.UidUser,
		&i.NumIDUser,
		&i.StrEmailUser,
		&i.StrPasswordUser,
		&i.StrNameUser,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uid_user, num_id_user, str_email_user, str_password_user, str_name_user, dtm_created_at, dtm_updated_at
FROM app_user
WHERE str_email_user = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.UidUser,
		&i.NumIDUser,
		&i.StrEmailUser,
		&i.StrPasswordUser,
		&i.StrNameUser,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO app_user (str_email_user, str_password_user, str_name_user)
VALUES ($1, $2, $3)
ON CONFLICT (str_email_user) DO UPDATE
    SET str_password_user = EXCLUDED.str_password_user,
        str_name_user     = EXCLUDED.str_name_user
RETURNING uid_user, num_id_user, str_email_user, str_password_user, str_name_user, dtm_created_at, dtm_updated_at
`

type UpsertUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.PasswordHash, arg.Name)
	var i AppUser
	err := row.Scan(
		&i.UidUser,
		&i.NumIDUser,
		&i.StrEmailUser,
		&i.StrPasswordUser,
		&i.StrNameUser,
		&i.DtmCreatedAt,
		&i.DtmUpdatedAt,
	)
	return i, err
}
